name: Python checks

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

permissions: read-all

jobs:
  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@e29cd923c49146a4fcc66eb0c8bea117e33ed9ce

      - run: uv pip install --system .[dev]

      - id: cache-ruff
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .ruff_cache
          key: ruff-${{ hashFiles('pyproject.toml') }}

      - id: run-ruff
        run: ruff format --diff .

  ruff-check:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@e29cd923c49146a4fcc66eb0c8bea117e33ed9ce

      - run: uv pip install --system .[dev]

      - id: cache-ruff
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .ruff_cache
          key: ruff-${{ hashFiles('pyproject.toml') }}

      - id: run-ruff-sarif
        run: |
          ruff check --output-format=sarif -o results.sarif .

      - uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3
        if: ( success() || failure() ) && contains('["success", "failure"]', steps.run-ruff-sarif.outcome)
        with:
          sarif_file: results.sarif

      - id: run-ruff
        if: failure() && contains('["failure"]', steps.run-ruff-sarif.outcome)
        run: |
          ruff check --output-format=github .

  bandit:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@e29cd923c49146a4fcc66eb0c8bea117e33ed9ce

      - run: uv pip install --system .[dev]

      - id: run-bandit-sarif
        run: |
          bandit --confidence-level 'medium' --severity-level 'medium' --recursive 'src' --format 'sarif' --output 'results.sarif'

      - uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3
        if: ( success() || failure() ) && contains('["success", "failure"]', steps.run-bandit-sarif.outcome)
        with:
          sarif_file: results.sarif

      - id: run-bandit
        if: failure() && contains('["failure"]', steps.run-bandit-sarif.outcome)
        run: |
          bandit --confidence-level 'medium' --severity-level 'medium' --recursive 'src'

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.13'
          cache: pip

      - uses: install-pinned/uv@dd0394506504875fca56dd387737d1bad6083768

      - run: uv pip install --system -e .[dev]

      - id: cache-mypy
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml') }}

      - run: mypy .

  pre-commit:
    runs-on: ubuntu-latest
    needs:
      - ruff-format
      - ruff-check
      - bandit

    permissions:
      contents: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            proxy.golang.org:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@e29cd923c49146a4fcc66eb0c8bea117e33ed9ce

      - run: uv pip install --system .[dev]

      - id: cache-pre-commit
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .pre-commit-cache
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pyproject.toml') }}

      - run: |
          pre-commit install
          pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: .pre-commit-cache
